version: '3'
services:
  ipfs_host:
    image: ipfs/kubo:latest
    volumes:
      - $ipfs_staging:/export
      - $ipfs_data:/data/ipfs
    ports:
      - 4001:4001
      - 4001:4001/udp
      - 8080:8080
      - 5001:5001
    environment:
      - IPFS_STAGING=/mnt/ipfs_staging/
      - IPFS_DATA=/mnt/ipfs_data/
    networks:
      my_network:
        ipv4_address: 172.28.5.1

  spellbook:
    image: spellbook:latest
    depends_on:
      - ipfs_host
    env_file:
      - docker_env.env
    environment:
      - IPFS_API=http://172.28.5.1:5001
    ports:
      - 42069:42069
    networks:
      - my_network

networks:
  my_network:
    external: true