[mypy]
explicit_package_bases = True
exclude = apps/
check_untyped_defs = False
mypy_path = webui

[mypy-bitcoin.*]
ignore_missing_imports = True

[mypy-bottle]
ignore_missing_imports = True

[mypy-faster_whisper]
ignore_missing_imports = True

[mypy-pbkdf2]
ignore_missing_imports = True

[mypy-mysql.*]
ignore_missing_imports = True

[mypy-websocket]
ignore_missing_imports = True

[mypy-tweepy]
ignore_missing_imports = True

[mypy-mastodon]
ignore_missing_imports = True

[mypy-ipfs_dict_chain.*]
ignore_missing_imports = True

[mypy-pynostr.*]
ignore_missing_imports = True

[mypy-fitnessfunction.*]
ignore_missing_imports = True

[mypy-model.*]
ignore_missing_imports = True

[mypy-rosettastone.*]
ignore_missing_imports = True

[mypy-genome]
ignore_missing_imports = True

[mypy-chromosome]
ignore_missing_imports = True

[mypy-encodingtype]
ignore_missing_imports = True
