[pytest]
testpaths = unittests
addopts = --cov=validators --cov=action --cov=trigger --cov=bips --cov=helpers --cov=data --cov=transactionfactory --cov=authentication --cov=decorators --cov=darwin --cov=webui --cov=listeners --cov=spellbookscripts --cov=inputs --cov=randomaddress --cov=linker --cov=spellbook --cov=spellbookserver --cov=texts --cov=import_llm_configs --cov=hot_wallet --cov=AESCipher --cov=bitcoinwand --cov=quickstart --cov=uptime_check --cov=replace_placeholders --cov-report=term-missing
filterwarnings =
    ignore:coroutine 'WebSocketHandler.broadcast' was never awaited:RuntimeWarning
    ignore:coroutine 'AsyncMockMixin._execute_mock_call' was never awaited:RuntimeWarning
    ignore:coroutine 'run_websocket_server' was never awaited:RuntimeWarning
    ignore:'bips.mnemonic' found in sys.modules:RuntimeWarning
