version: '3'
services:
  ipfs_host:
    image: ipfs/kubo:latest
    volumes:
      - $IPFS_STAGING:/export
      - $IPFS_DATA:/data/ipfs
    ports:
      - 4001:4001
      - 4001:4001/udp
      - 8080:8080
      - 5001:5001
    environment:
      - IPFS_STAGING=/mnt/ipfs_staging/
      - IPFS_DATA=/mnt/ipfs_data/
    networks:
      valyria:
        ipv4_address: 172.28.5.1

  spellbook:
    image: valyriantech/spellbook:latest
    depends_on:
      - ipfs_host
    env_file:
      - docker_env.env
    environment:
      - IPFS_ENABLE_IPFS=true
      - IPFS_API_HOST=172.28.5.1
      - IPFS_API_PORT=5001
    ports:
      - 42069:42069
    networks:
      - valyria

networks:
  valyria:
    driver: bridge
    ipam:
     config:
       - subnet: 172.28.0.0/16